---    
  - name: Install Python3
    register: python3_installed
    yum: 
      name: "{{ item }}" 
      update_cache: yes 
      state: latest
    with_items:
      - python34 
      - python-pip
      
  - name: Update pip
    pip:
      name: "pip"
      state: latest
    when: python3_installed|success