---
  - name: Install nginx
    become: true
    yum: 
      name: nginx
      state: present
      
  - name: Copy nginx configuration
    become: true
    template: 
        src: default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
    
  - name: Copy proxy params
    become: true
    file: 
        src: proxy_params
        dest: /etc/nginx/proxy_params
    
  - name: restart nginx
    become: true
    service: 
      name: nginx 
      state: restarted 
      enabled: yes