---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    project_name: "Deployer"
    project_path: "/home/centos/"
    server_domain_or_IP: "127.0.0.1"
    first_run: false
  roles:
    - user
    - common
    - supervisor
    #- gunicorn
    #- nginx
    #- deployer
    
    #- packer
    #- terraform
    
    
