---
- hosts: all
  gather_facts: yes
  vars:
    project_name: "Deployer"
    project_path: "/home/centos/"
    server_domain_or_IP: "127.0.0.1"
    update_yum: false
    update_pip: false
  roles:
    - user
    - common
    - deployer
    - web
    - nginx
    
    #- packer
    #- terraform
    
    
