---
- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - common
    - user
    #- ansible
    #- packer
    #- terraform
    - python 
    #- nginx
    #- gunicorn
    - flask
    - deployer
    
