Vagrant.configure(2) do |config|

  config.vm.box = "phase2/centos-7"
  host = RbConfig::CONFIG['host_os']
  
  if host =~ /darwin/
    cpus = `sysctl -n hw.ncpu`.to_i
    mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
    local_provision = "ansible"
    
  elsif host =~ /linux/
    cpus = `nproc`.to_i
    mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
    local_provision = "ansible"
    
   else # Windows 
    local_provision = "ansible_local"
    cpus = 2
    mem = 1024
  end
  
  config.vm.define :VagrantPacker do |t|
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", mem]
    vb.customize ["modifyvm", :id, "--cpus", cpus]
    end
    config.vm.network :forwarded_port, guest: 80, host: 8080
    config.vm.network :forwarded_port, guest: 443, host: 8443
    config.vm.network :forwarded_port, guest: 8000, host: 8000  
    config.vm.network :forwarded_port, guest: 9001, host: 9001  

    config.vm.provision local_provision do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = {}
    end
    
  end