--- 
  - name: prepare necessary directories
    file: 
      path: "{{item}}"
      state: directory 
      recurse: yes
      owner: "{{deployer.config.user}}"
    with_items:
      - "{{deployer.app.dir}}"
  
  - name: Install Deployer
    copy: 
      src: deployer.py
      dest: "{{deployer.app.dir}}/deployer.py"
      