---
  - name: Install Deployer
    copy: 
      src: deployer.py
      dest: ~/deployer.py
      
  #- name: Start Deployer Directly
  #  shell: python ~/deployer.py
    
  #- name: Start Deployer
  #  shell: gunicorn --bind 0.0.0.0:8000 wsgi