--- 
  - name: prepare deployer directories
    become: true
    become_user: centos
    file: 
      path: "{{item}}"
      state: directory 
      recurse: yes
      owner: "{{deployer.config.user}}"
    with_items:
      - "{{deployer.app.dir}}"
  
  - name: Install Deployer
    become: true
    become_user: centos
    copy: 
      src: deployer.py
      dest: "{{deployer.app.dir}}/deployer.py"
      owner: "{{deployer.config.user}}"
  
  - name: Install Deployer wsgi
    become: true
    become_user: centos
    copy: 
      src: wsgi.py
      dest: "{{deployer.app.dir}}/wsgi.py"
      owner: "{{deployer.config.user}}"
      