---
  - name: check if EPEL is installed
    shell: /usr/bin/rpmquery epel-release
    register: epel_installed
    ignore_errors: true
    changed_when: false
    
  - name: install EPEL
    yum:
      pkg: epel-release
      state: installed
      
  - name: clean yum metadata on first run
    shell: /usr/bin/yum clean all
    
  - name: upgrade all packages on first run
    yum:
      name: '*'
      state: latest

  - name: Install Common Packages
    register: commoninstalled
    yum: 
      name: "{{ item }}"
      update_cache: yes 
      state: present
    with_items:
      - vim
