---
  - name: clean yum metadata on first run
    become: yes
    command: /usr/bin/yum clean all
    when: update_yum == true
    
  - name: upgrade all packages on first run
    become: yes
    yum:
      name: '*'
      state: latest
      update_cache: yes 
    when: update_yum == true

  - name: check if EPEL is installed
    become: yes
    command: /usr/bin/rpmquery epel-release
    register: epel_installed
    ignore_errors: true
    changed_when: false

  - name: install EPEL
    become: yes
    yum:
      pkg: epel-release
      state: installed
    when: epel_installed|failed
      
  - name: install yum packages
    become: yes
    yum: name={{ item }} state=present
    with_items:
      - ansible
      - vim
      - python34 
      - python-pip
      
  - name: Update pip
    become: yes
    pip:
      name: "pip"
      state: latest
    when: update_pip == true
      
  - name: install pip packages
    become: yes
    pip: name={{ item }} state=present
    with_items:
      - flask
      
  - name: prepare centos directories
    become: yes
    file: 
      path: /opt
      state: directory 
      owner: "centos"
      group: "centos"