gunicorn:
  app:
    name: "deployer"
    dir: /opt/deployer
    
  config:
    dir: /opt/gunicorn/etc
    executable: /opt/gunicorn/etc/run_gunicorn.sh
    user: centos
    group: centos
    workers: 3
    max_requests: 1
  
  runtime: 
    dir: /opt/gunicorn/var/run
    socket: /opt/gunicorn/var/run/gunicorn.sock
    
  log:
    dir: /opt/gunicorn/var/log
    file: /opt/gunicorn/var/log/supervisord.log
    
supervisor:
  runtime:
    socket: /var/run/supervisord.sock
    pidfile: /var/run/supervisord.pid

  config:
    dir: /etc/supervisor
    file: /etc/supervisor/supervisord.conf
    appdir: /etc/supervisor/conf.d

  log:
    dir: /var/log/supervisor
    file: /var/log/supervisor/supervisord.log
    